import type React from "react";

/** Form and row primitives shared by the inventory components. */
export const inv: Record<string, React.CSSProperties> = {
	form: {
		backgroundColor: "#fff",
		borderRadius: 8,
		padding: "1rem",
		marginBottom: "1rem",
		boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
	},
	formGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
		gap: "0.75rem",
		marginBottom: "0.75rem",
	},
	full: { gridColumn: "1 / -1" },
	label: {
		display: "block",
		fontSize: "0.75rem",
		color: "#718096",
		marginBottom: 4,
		fontWeight: 600,
	},
	input: {
		width: "100%",
		padding: "0.4rem 0.6rem",
		borderRadius: 6,
		border: "1px solid #e2e8f0",
		fontSize: "0.85rem",
		boxSizing: "border-box",
	},
	checkRow: {
		display: "flex",
		alignItems: "center",
		gap: "0.4rem",
		fontSize: "0.85rem",
		color: "#2d3748",
	},
	checkGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
		gap: "0.25rem 0.75rem",
	},
	fieldset: {
		border: "1px solid #e2e8f0",
		borderRadius: 6,
		padding: "0.5rem 0.75rem 0.6rem",
		margin: 0,
	},
	legend: {
		fontSize: "0.75rem",
		color: "#718096",
		fontWeight: 600,
		padding: "0 4px",
	},
	hint: { fontSize: "0.75rem", color: "#a0aec0", marginTop: 6 },
	buttonRow: { display: "flex", gap: "0.5rem", flexWrap: "wrap" },
	primaryBtn: {
		padding: "0.5rem 1.5rem",
		backgroundColor: "#3182ce",
		color: "#fff",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontWeight: 600,
		fontSize: "0.85rem",
	},
	secondaryBtn: {
		padding: "4px 10px",
		backgroundColor: "transparent",
		color: "#3182ce",
		border: "1px solid #3182ce",
		borderRadius: 4,
		cursor: "pointer",
		fontSize: "0.75rem",
	},
	neutralBtn: {
		padding: "4px 10px",
		backgroundColor: "transparent",
		color: "#4a5568",
		border: "1px solid #cbd5e0",
		borderRadius: 4,
		cursor: "pointer",
		fontSize: "0.75rem",
	},
	dangerBtn: {
		padding: "4px 10px",
		backgroundColor: "transparent",
		color: "#e53e3e",
		border: "1px solid #e53e3e",
		borderRadius: 4,
		cursor: "pointer",
		fontSize: "0.75rem",
	},
	warnBox: {
		backgroundColor: "#fefce8",
		border: "1px solid #fde68a",
		borderRadius: 6,
		padding: "0.5rem 0.75rem",
		marginBottom: "0.75rem",
		fontSize: "0.8rem",
		color: "#713f12",
	},
	infoBox: {
		backgroundColor: "#ebf8ff",
		border: "1px solid #90cdf4",
		borderRadius: 6,
		padding: "0.5rem 0.75rem",
		marginBottom: "0.75rem",
		fontSize: "0.8rem",
		color: "#2a4365",
	},
};
